repos:
  -  repo: https://github.com/digitalpulp/pre-commit-php.git
     rev: 1.4.0
     hooks:
       - id: php-stan
         pass_filenames: false
       - id: php-lint
  -  repo: local
     hooks:
       - id: pest
         name: Pest PHP - Automated Test Suite
         entry: ./vendor/bin/pest
         language: system
         types: [php]
         stages: [commit]
         require_serial: true
         pass_filenames: false
